export const CONFIG = {
	TOAST_ERROR_DURATION_MS: Number(process.env.TOAST_ERROR_DURATION_MS),
	MAX_POSTS_BY_AUTHOR_ID: Number(process.env.MAX_POSTS_BY_AUTHOR_ID),
	MAX_POST_REPLIES: Number(process.env.MAX_POST_REPLIES),
	MAX_POST_MESSAGE_LENGTH: Number(process.env.MAX_POST_MESSAGE_LENGTH),
	MAX_POLL_CHOICES: Number(process.env.MAX_POLL_CHOICES),
	POSTS_PER_PAGE: Number(process.env.POSTS_PER_PAGE),
	SCROLL_THRESHOLD_IN_PX: Number(process.env.SCROLL_THRESHOLD_IN_PX)
}
