export const CONFIG = {
	TOAST_ERROR_DURATION_MS: Number(process.env.TOAST_ERROR_DURATION_MS),
	MAX_POSTS_BY_AUTHOR_ID: Number(process.env.MAX_POSTS_BY_AUTHOR_ID),
	MAX_POST_REPLIES: Number(process.env.MAX_POST_REPLIES),
	MAX_POST_MESSAGE_LENGTH: Number(process.env.MAX_POST_MESSAGE_LENGTH),
}
